apiVersion: v1
kind: ReplicationController
metadata:
  name: rutherford-spe-extractor
  namespace: 4ceed
spec:
  replicas: 1
  selector:
    app: rutherford-spe-extractor 
  template:
    metadata:
      labels:
        app: rutherford-spe-extractor 
    spec:
      containers:
      - name: rutherford-spe-extractor
        image: t2c2/rutherford-spe-extractor
        env:
        - name: "RABBITMQ_URL"
          value: "amqp://guest:guest@rabbitmq:5672/%2f"
        imagePullPolicy: Always
