apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
  namespace: 4ceed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo:3.2.1
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: nfs-storage
          mountPath: "/data/db"
        resources:
          requests:
            memory: "4096Mi"
            cpu: "1000m"
          limits:
            memory: "8192Mi"
            cpu: "2000m"
      volumes:
        - name: storage
          emptyDir: {}
        - name: nfs-storage
          hostPath:
            path: "/mnt/nfs/mongodb" 
