apiVersion: v1
kind: ReplicationController
metadata:
  name: es
  labels:
    component: elasticsearch
  namespace: 4ceed
spec:
  replicas: 1
  selector:
    component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: es
        image: t2c2/docker-elasticsearch-kubernetes:2.4.0
        env:
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: "/data/es"
          name: storage 
      volumes:
      - name: storage 
        emptyDir: {}
      - name: nfs-storage 
        hostPath:
          path: "/mnt/nfs/es-data"
