apiVersion: v1
kind: Service
metadata:
  name: t2c2curatorsvc 
  labels:
    app: t2c2curatorsvc 
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    name: http
    nodePort: 32500
  selector:
    app: t2c2curator
