apiVersion: v1
kind: ReplicationController
metadata:
  name: t2c2uploader 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: t2c2uploader 
    spec:
      containers:
      - name: t2c2uploader 
        image: t2c2/4ceeduploader:16.09.2
        ports:
        - containerPort: 2309 
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "4096Mi"
            cpu: "2000m"
